version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_java
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_java
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
  seata-server:
    image: seataio/seata-server:latest
    hostname: seata-server
    ports:
      - 8091:8091
      - 7091:7091
    environment:
      - SEATA_PORT=8091
    expose:
      - 8091
      - 7091
#  nacos:
#    image: nacos/nacos-server
#    container_name: nacos_java
#    ports:
#      - "8848:8848"
#    environment:
#      - MODE=standalone
#    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: