server:
  port: 9001

spring:
  application:
    name: user-service

  # Database Configuration

#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/User?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: postgres
#    password: xiqNDNRBdZCu99Bvgg3F
#
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456
#
#  mail:
#    host: smtp.163.com
#    username: allworknofun@163.com
#    password: FMLPDXWWKVFIPRBB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
        mail:
            starttls:
                enable: true
                required: true
            ssl:
                enable: true
            default-encoding: UTF-8



# Configure MyBatis-Plus to print SQL logs
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# configure aws s3
aws:
  s3:
    bucket-name: java-ecommerce
    region: ap-southeast-1


# Set log level, ERROR/WARN/INFO/DEBUG, default is to show only INFO and above

logging:
  level:
    root: INFO
