CREATE DATABASE IF NOT EXISTS Coupon;
CREATE DATABASE IF NOT EXISTS Orders;
CREATE DATABASE IF NOT EXISTS Product;
CREATE DATABASE IF NOT EXISTS Nacos;
CREATE DATABASE IF NOT EXISTS Users;


GRANT ALL PRIVILEGES ON Nacos.* TO 'ecommerce'@'%';
GRANT ALL PRIVILEGES ON Product.* TO 'ecommerce'@'%';
GRANT ALL PRIVILEGES ON Orders.* TO 'ecommerce'@'%';
GRANT ALL PRIVILEGES ON Coupon.* TO 'ecommerce'@'%';
GRANT ALL PRIVILEGES ON Users.* TO 'ecommerce'@'%';

FLUSH PRIVILEGES;